stdin: true # The agent requires interactive input from stdin to get the initial target market/theme.
name: Trading News Agent
summary: An AI agent that tracks financial news for user-specified markets/sectors/themes, identifies relevant companies, fetches news, extracts and prunes facts, and generates hourly investment recommendations with justifications and hypothetical scenarios.
environment_variables:
  - name: GEMINI_API_KEY
    value: <your_gemini_api_key>
    description: The API key for authenticating with the Google Gemini API.